#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Codex agent
##############################################################################

APP_BASE_NAME=`basename "$0"`
APP_HOME=`cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P`
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

GRADLE_OPTS="-Xmx64m -Xms64m"

if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi

exec "$JAVA" $JVM_OPTS $GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
