package vectorregnum.core;

public enum FaultCode {
    UNKNOWN_SIGIL,
    UNKNOWN_ELEMENT,
    UNKNOWN_SHAPE,
    OPERAND_COUNT,
    TYPE_MISMATCH,
    INVALID_NUMBER,
    ORIGIN_REQUIRED,
    ORIGIN_ALREADY_SET,
    VECTOR_ALREADY_SET,
    DIRECTION_REQUIRED,
    ELEMENT_ALREADY_SET,
    SHAPE_ALREADY_SET,
    SHAPE_REQUIRED,
    NOTHING_TO_AMPLIFY,
    MISSING_COMPONENT,
    MISSING_EXECUTE,
    INSTRUCTION_AFTER_EXECUTE,
    INSUFFICIENT_MANA,
    NUMERIC_OVERFLOW
}
