#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

readonly REPO_ROOT="/home/iank/Desktop/my mods/mods-editing/vector-regnum"
readonly DESKTOP_LAUNCHER="/home/iank/Desktop/Vector-Regnum.desktop"
readonly SERVER_UNIT="vector-regnum-local-server.service"
readonly SERVER_PORT="25575"
readonly CLIENT_LOG="$REPO_ROOT/run/client/logs/latest.log"
readonly WIZARD_STARTED_EPOCH="$(date +%s)"

fail() {
  printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

banner "Vector-Regnum priority 21 local visual gate"

stage "Isolated launcher preflight"
say "This wizard never opens, focuses, types into, or closes a window."
say "You will operate Minecraft yourself; the wizard only checks files, logs, the owned unit, and port 25575."
[[ "$(hostname)" == "nixos" && "$(whoami)" == "iank" ]] ||
  fail "Run this only as iank on the main PC named nixos."
[[ -x "$DESKTOP_LAUNCHER" ]] || fail "The real desktop launcher is missing or not executable."
grep -Fxq 'Exec=/run/current-system/sw/bin/bash "/home/iank/Desktop/my mods/mods-editing/vector-regnum/scripts/local-play.sh"' "$DESKTOP_LAUNCHER" ||
  fail "The desktop shortcut does not target this checkout's guarded local launcher."
"$REPO_ROOT/scripts/local-play.sh" --check-config >/dev/null ||
  fail "The isolated server configuration did not pass its guard."
[[ "$(systemctl --user show "$SERVER_UNIT" --property=LoadState --value 2>/dev/null || printf 'not-found\n')" == "not-found" ]] ||
  fail "$SERVER_UNIT already exists; do not start a second launcher."
if ss -H -ltn "sport = :$SERVER_PORT" | grep -q .; then
  fail "Port $SERVER_PORT is already in use."
fi
printf '  %s✓ preflight passed%s\n' "$GREEN" "$RESET"
pause "Press Enter for the human-controlled launch step."

stage "Launch and inspect the Veil backend"
step "On your desktop, double-click Play Vector-Regnum. Do not use another launcher."
step "Wait for Minecraft 1.21.1 to enter the isolated flat world; this can take about a minute."
step "Confirm there is no Connection refused, Disconnected, or incompatible-mod screen."
confirm "Did the real desktop shortcut reach an in-world view?" ||
  fail "Visual gate not attested; nothing was marked complete."
step "Press T, run /vectorregnum devkit, and close chat. This unlocks and refills the isolated test player."
step "Run /vectorregnum showcase. Look for a circle or ring near you, a directed Firebolt gesture, and an expanding Ice Nova gesture."
step "The effects should stay near their origin or path and fade within about 15 seconds. A brief bright flare is fine; a stuck full-screen layer, giant opaque rectangle, or magenta/black missing texture is not."
step "Run /vectorregnum circle vm_starter, then /vectorregnum circle cast. Confirm the authored Vector Step has a readable origin/direction cue and moves you without leaving a permanent effect."
step "Wait a few seconds between casts. Run /vectorregnum library cast aegis_shell, then /vectorregnum library cast mage_light. Look for a bounded ward/aura and a localized light effect."
step "Veil adds colored motes, soft glow, and local spell lighting. The log proves which backend loaded; your job is only to reject obviously broken or unreadable rendering."
confirm "Did the showcase, authored cast, and two library casts appear near their true locations, remain readable, and end without broken or stuck rendering?" ||
  fail "Veil presentation gate not attested; nothing was marked complete."

stage "Verify elemental identity and guide"
step "Run /vectorregnum mana. Record the permanent natural element and current mutable channel shown in chat."
step "Run /vectorregnum mana attune ice, then /vectorregnum mana again. Confirm the channel is now ice and the natural element is unchanged."
step "Run /vectorregnum mana attune arcane afterward so this isolated test player returns to neutral raw-mana tuning."
confirm "Did channel attunement change independently while the natural element stayed fixed?" ||
  fail "Natural-element permanence/channel-attunement gate not attested; nothing was marked complete."
step "Run /vectorregnum guide, open the Vector-Regnum Field Manual v11, and open Elemental Identity."
step "Confirm it explains one permanent natural element, mutable channel attunement, Arcane as neutral raw mana, rare Void, Ice terminology, and the 100/75/50/25% bands."
confirm "Was the priority-21 elemental chapter present, legible, and free of stale Frost terminology?" ||
  fail "Field Manual v11 gate not attested; nothing was marked complete."

stage "Exercise reload, LOD, and accessibility fallbacks"
step "Press F3+T, wait for the reload-complete message, then run /vectorregnum showcase again."
confirm "Did the same effects render after resource reload without a broken or permanently missing layer?" ||
  fail "Resource-reload gate not attested; nothing was marked complete."
step "Press O. Set quality to Minimal, enable Reduced Motion and Photosensitive, then close the screen."
step "Run /vectorregnum showcase once more. The expressive Veil layers may disappear, but origin, direction, area, danger, and impact cues must remain readable."
confirm "Did the accessible low-LOD path preserve the mandatory truth telegraphs?" ||
  fail "Accessible fallback gate not attested; nothing was marked complete."
step "Press O and restore Full quality, Reduced Motion off, and Photosensitive off before closing Minecraft."

stage "Close normally and prove cleanup"
step "Close Minecraft normally from its own menu or window. Do not close another application."
pause "After Minecraft and its launcher terminal have closed, press Enter."
for _ in {1..30}; do
  unit_state="$(systemctl --user show "$SERVER_UNIT" --property=LoadState --value 2>/dev/null || printf 'not-found\n')"
  if [[ "$unit_state" == "not-found" ]] && ! ss -H -ltn "sport = :$SERVER_PORT" | grep -q .; then
    break
  fi
  sleep 1
done
[[ "$unit_state" == "not-found" ]] || fail "$SERVER_UNIT did not unload after Minecraft closed."
if ss -H -ltn "sport = :$SERVER_PORT" | grep -q .; then
  fail "Port $SERVER_PORT is still listening after cleanup."
fi
[[ -f "$CLIENT_LOG" ]] || fail "The client log was not created."
(( $(stat -c %Y "$CLIENT_LOG") >= WIZARD_STARTED_EPOCH )) ||
  fail "The client log predates this wizard run; the desktop shortcut was not freshly exercised."
grep -Fq 'Connecting to 127.0.0.1, 25575' "$CLIENT_LOG" ||
  fail "The client log does not prove the explicit IPv4 quick-play endpoint."
grep -Fq 'Vector-Regnum NeoForge initialized' "$CLIENT_LOG" ||
  fail "The client log does not prove Vector-Regnum initialized on NeoForge."
grep -Fq 'Vector-Regnum presentation backend: veil-4.4.1 (Veil 4.4.1)' "$CLIENT_LOG" ||
  fail "The client log does not prove the pinned Veil backend activated."
quasar_loaded="$(rg -o -m1 'Loaded ([0-9]+) quasar particles' -r '$1' "$CLIENT_LOG" || true)"
case "$quasar_loaded" in
  ''|*[!0-9]*) fail "The client log does not prove the bounded Quasar vocabulary loaded." ;;
esac
(( quasar_loaded >= 59 )) ||
  fail "The client log proves only $quasar_loaded Quasar motifs loaded; the priority-21 vocabulary has 59."
if rg -i 'Veil presentation backend failed|Veil Quasar emitter did not load|quasar registry loading errors' "$CLIENT_LOG" >/dev/null; then
  fail "The client log records a Veil or Quasar failure."
fi
point_light_warning='Failed to validate shader (veil:light/point) : active samplers with a different type refer to the same texture image unit'
reload_line="$(rg -n -m1 '\[Debug\]: Reloaded resource packs' "$CLIENT_LOG" | cut -d: -f1 || true)"
[[ -n "$reload_line" ]] || fail "The client log does not prove the requested F3+T resource reload completed."
point_light_warning_before_reload="$(head -n "$reload_line" "$CLIENT_LOG" | rg -F -c "$point_light_warning" || true)"
point_light_warning_after_reload="$(tail -n "+$reload_line" "$CLIENT_LOG" | rg -F -c "$point_light_warning" || true)"
unexpected_shader_validation="$(rg 'Failed to validate shader' "$CLIENT_LOG" | rg -F -v "$point_light_warning" || true)"
[[ -z "$unexpected_shader_validation" ]] || fail "The client log records an unexpected Veil shader-validation warning."
(( point_light_warning_before_reload <= 2 )) || fail "The known Veil point-light warning repeated more than twice before resource reload."
(( point_light_warning_after_reload <= 2 )) || fail "The known Veil point-light warning repeated more than twice after resource reload."
grep -Fq 'Stopping!' "$CLIENT_LOG" ||
  fail "The client log does not show Minecraft's normal shutdown path."

mkdir -p -- "$REPO_ROOT/visual-evidence"
evidence_file="$REPO_ROOT/visual-evidence/main-pc-priority21-visual-attestation.txt"
{
  printf 'status=passed\n'
  printf 'checked_at_utc=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'checked_by=%s@%s\n' "$(whoami)" "$(hostname)"
  printf 'launcher=%s\n' "$DESKTOP_LAUNCHER"
  printf 'endpoint=127.0.0.1:%s\n' "$SERVER_PORT"
  printf 'renderer=veil-4.4.1\n'
  printf 'point_light_warnings=%s_before_reload;%s_after_reload\n' "$point_light_warning_before_reload" "$point_light_warning_after_reload"
  printf 'observed=natural-element; mutable-channel; ice-nova; guide-v7; authored-spells; library-spells; resource-reload; low-lod; reduced-motion; photosensitive; truth-fallback; normal-cleanup\n'
  printf 'server_unit=not-found\n'
  printf 'port_%s=free\n' "$SERVER_PORT"
} > "$evidence_file"
printf '  %s✓ wrote attestation%s %s\n' "$GREEN" "$RESET" "$evidence_file"

finish
say "Priority 21 now has its required local human evidence. Give the result to the project agent so it can update ROADMAP.md and the handoff docs."
