allow-flight=true
difficulty=peaceful
enable-command-block=true
enable-query=false
enable-rcon=false
enforce-secure-profile=false
force-gamemode=true
gamemode=creative
generate-structures=false
level-name=vector-regnum-test
level-type=minecraft\:flat
max-players=4
motd=Vector-Regnum Visual Test World
online-mode=false
server-port=25575
server-ip=127.0.0.1
simulation-distance=4
spawn-protection=0
view-distance=6
